apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoapp-deployment
  namespace: {{ .Values.namespace }}
  labels: 
    app: djangoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: djangoapp
  template:
    metadata:
      labels:
        app: djangoapp
    spec:
      # imagePullSecrets:
      # - name: my-registry-key
      containers:
      - name: djangoapp
        image: appu234/django-app:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: djangoapp-internal-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: djangoapp
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    