apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deployment
  namespace: combined
  labels: 
    app: springapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      # imagePullSecrets:
      # - name: my-registry-key
      containers:
      - name: springapp
        image: appu234/final-java-app:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springapp-internal-service
  namespace: combined
spec:
  selector:
    app: springapp
  # type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    # nodePort: 30345
    