apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proper-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "proper-chart.name" . }}
    helm.sh/chart: {{ include "proper-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "proper-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: {{ include "proper-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec: 
      containers:
        - name: {{ .Chart.Name }} 
          # image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
           