namespace: k8s-eval-poc
ingress: ba5dbac.kyma-stage.shoot.live.k8s-hana.ondemand.com
Deployment:
  mongo:
    name: mongodb-deployment
    labels:
      app: mongodb
    
    container-name: mongodb
    container-image: mongo
    container-port: 27017